#!/usr/bin/env python3
import torch
import threading

# hmin = (default: -0.02) # lower base (starting point) of each bin-cylinder
# hmax_list = (default: [0.01, 0.02, 0.03, 0.04]) # upper base (ending point) of each bin-cylinder
# num_point = (default: 20000) # number of points passed to the neural network to search for grasps
# num_view = (default: 300) number of views generated by the neural network to search for grasps #! CANNOT be changed
# num_angle = (default: 12) # for each view, number of angles searched by the neural network to search for grasps #! CANNOT be changed
# num_depth = (default: 4) # number of bins-cylinders #! CANNOT be changed
# cylinder_radius = (default: 0.05) # base radius of each bin-cylinder
# finger_width = (default: 0.01) # width of the gripper fingers (assuming square cross-section)
# finger_length = (default: 0.06) # length of the gripper fingers
# GRASP_MAX_WIDTH = (default: 0.10) # maximum gripper opening (inner faces)
# GRASP_MIN_WIDTH = (default: 0) # minimum gripper opening (inner faces)
# GRASP_MAX_TOLERANCE = (default: 0.05)
# THRESH_GOOD = (default: 0.7) # threshold to consider a grasp as good
# THRESH_BAD = (default: 0.1) # threshold to consider a grasp as bad
# voxel_size = (default: 0.005) # voxel size for point cloud downsampling
# collision_thresh = (default: 0.01) # collision threshold for the gripper, degree of gripper penetration into the point cloud
# approach_dist = (default: 0.05) distance the gripper approaches along the approach direction before closing the fingers
# num_best_grasps = (default: 50) number of best grasps selected and visualized




#! FOR THE SPHERE
# ----- Parameters -----
hmin = -0.01 #! OTTIMIZZATO
hmax_list = [0.01, 0.02, 0.03, 0.04] #! OTTIMIZZATO
num_point = 10000 #! OTTIMIZZATO (changes together with vocel_size)
num_view = 300
num_angle = 12
num_depth = len(hmax_list)
cylinder_radius = 0.02 #! OTTIMIZZATO

# ----- Parameters for gripper -----
finger_width = 0.01
finger_length = 0.06
GRASP_MAX_WIDTH = 0.15
GRASP_MIN_WIDTH = 0
GRASP_MAX_TOLERANCE = 0.05
THRESH_GOOD = 0.7
THRESH_BAD = 0.1

# ----- Parameters for collision detection -----
voxel_size = 0.01 #! OTTIMIZZATO (changes together with num_point)
collision_thresh = 0.01
approach_dist = 0.01 #! OTTIMIZZATO




#! FOR THE BOX (prova_box_5x5x5.pcd)
# # ----- Parameters -----
# hmin = -0.01 #! OTTIMIZZATO
# hmax_list = [0.01, 0.02, 0.03, 0.04] #! OTTIMIZZATO
# num_point = 2000 #! OTTIMIZZATO (changes together with vocel_size)
# num_view = 300
# num_angle = 12
# num_depth = len(hmax_list)
# cylinder_radius = 0.02 #! OTTIMIZZATO

# # ----- Parameters for gripper -----
# finger_width = 0.01
# finger_length = 0.06
# GRASP_MAX_WIDTH = 0.15
# GRASP_MIN_WIDTH = 0
# GRASP_MAX_TOLERANCE = 0.05
# THRESH_GOOD = 0.7
# THRESH_BAD = 0.1

# # ----- Parameters for collision detection -----
# voxel_size = 0.01 #! OTTIMIZZATO (changes together with num_point)
# collision_thresh = 0.01
# approach_dist = 0.05 #! OTTIMIZZATO




# ----- Global variables for the visualization -----
vis = None
pcd_vis = None
gripper_list = []
net = None
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
latest_points = None
latest_gg = None
pending_update = False
terminate = False
lock = threading.Lock()
terminate_visualization = False
num_best_grasps = 5