#!/usr/bin/env python3

"""
This file contains all the parameters the user can set and a brief description for each of them.
    - hmin = (default: -0.02) # lower base (starting point) of each bin-cylinder
    - hmax_list = (default: [0.01, 0.02, 0.03, 0.04]) # upper base (ending point) of each bin-cylinder
    - num_point = (default: 20000) # number of points passed to the neural network to search for grasps
    - num_view = (default: 300) number of views generated by the neural network to search for grasps #! CANNOT be changed
    - num_angle = (default: 12) # for each view, number of angles searched by the neural network to search for grasps #! CANNOT be changed
    - num_depth = (default: 4) # number of bins-cylinders #! CANNOT be changed
    - cylinder_radius = (default: 0.05) # base radius of each bin-cylinder
    - finger_width = (default: 0.01) # width of the gripper fingers (assuming square cross-section)
    - finger_length = (default: 0.06) # length of the gripper fingers
    - GRASP_MAX_WIDTH = (default: 0.10) # maximum gripper opening (inner faces)
    - GRASP_MIN_WIDTH = (default: 0) # minimum gripper opening (inner faces)
    - GRASP_MAX_TOLERANCE = (default: 0.05)
    - THRESH_GOOD = (default: 0.7) # threshold to consider a grasp as good
    - THRESH_BAD = (default: 0.1) # threshold to consider a grasp as bad
    - voxel_size = (default: 0.005) # voxel size for point cloud downsampling
    - collision_thresh = (default: 0.01) # collision threshold for the gripper, degree of gripper penetration into the point cloud
    - approach_dist = (default: 0.05) distance along the approach direction between the grasping point (center of the grasp) and the gripper point (center of the gripper, at the fingers tip)
    - num_best_grasps = (default: 50) number of best grasps selected and visualized
"""


# ----- Parameters for the net -----
hmin = -0.01
hmax_list = [0.01, 0.02, 0.03, 0.04]
num_point = 2000
num_view = 300
num_angle = 12
num_depth = len(hmax_list)
cylinder_radius = 0.02

# ----- Parameters for the gripper -----
finger_width = 0.02
finger_length = 0.07
GRASP_MAX_WIDTH = 0.085
GRASP_MIN_WIDTH = 0
GRASP_MAX_TOLERANCE = 0.05
THRESH_GOOD = 0.7
THRESH_BAD = 0.1

# ----- Parameters for collision detection -----
voxel_size = 0.01 #! voxel_size (in parameters.py) == resolution (in nbv_params.yaml)
collision_thresh = 0.01
approach_dist = 0.03

# ----- Parameters for visualization (Open3D) -----
num_best_grasps = 10

# ----- Parameters to manually create the plane -----
min_x = 2.00
max_x = 2.50
min_y = -1.00
max_y = -0.50
# z_plane = 0.20 # <-- SIMULATION environment #! z_plane (in parameters.py) == ws_filter__min_z (in nbv_params_simEnv.yaml)
z_plane = 0.06 # <-- REAL environment #! z_plane (in parameters.py) == ws_filter__min_z (in nbv_params_realEnv.yaml)